project:
  type: book

book:
  title: "fhe-intro-book"
  author: "camcos-sjsu"
  date: "September 28, 2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: general/aux-fn.qmd
      chapters:
        - general/intravector-sums.qmd
        - general/higher-moments.qmd
        - general/taylor-approx.qmd
        - general/sqrt-user-input.qmd
        - general/logarithm.qmd
    - part: division/division.qmd
      chapters:
      - division/geometric-series.qmd
      - division/newtons-method.qmd
      - division/hybrid-approach.qmd
      - division/softmax.qmd
    - discrete-math.qmd
    - part: sign/sign-fn.qmd
      chapters:
        - sign/logistic.qmd
        - sign/tanh.qmd
        - sign/sign-appl.qmd
    - part: sorting/sorting.qmd
      chapters:
        - sorting/bubble.qmd
        - sorting/sorting-better.qmd
    - max.qmd
    - part: difference-matrix/difference-matrix.qmd
      chapters:
        - difference-matrix/mode.qmd
        - difference-matrix/median.qmd
    - part: correlation-related/correlation-related.qmd
      chapters:
        - correlation-related/two-coeff.qmd
        - correlation-related/linear-regression.qmd
    - part: other/other.qmd
      chapters:
        - other/matrix-multiplication.qmd
        - other/shannon-entropy.qmd
        - other/adaptive-division.qmd
        - other/logarithm-rev.qmd
    - lit-review.qmd

  appendices:
    - discrete-computational.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    axe: true
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

# editor: visual