project:
  type: book

book:
  title: "fhe-intro-book"
  author: "camcos-sjsu"
  date: "September 28, 2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: general/intro.qmd
      chapters:
        - general/intravector-sums.qmd
        - general/higher-moments.qmd
        - general/taylor-approx.qmd
        - general/sqrt-user-input.qmd
        - general/logarithm.qmd
    - part: division/intro.qmd
      chapters:
      - division/geometric-series.qmd
      - division/newtons-method.qmd
      - division/hybrid-approach.qmd
      - division/softmax.qmd
    - discrete-math.qmd
    - part: sign/intro.qmd
      chapters:
        - sign/logistic.qmd
        - sign/tanh.qmd
        - sign/applicability.qmd
    - part: sorting/intro.qmd
      chapters:
        - sorting/bubble.qmd
        - sorting/improvements.qmd
        - sorting/max.qmd
    - part: difference-matrix/intro.qmd
      chapters:
        - difference-matrix/mode.qmd
        - difference-matrix/median.qmd
    - part: correlation-related/intro.qmd
      chapters:
        - correlation-related/two-coeff.qmd
        - correlation-related/linear-regression.qmd
    - part: other/intro.qmd
      chapters:
        - other/matrix-multiplication.qmd
        - other/shannon-entropy.qmd
        - other/adaptive-division.qmd
        - other/logarithm-revisited.qmd
    - lit-review.qmd
    - part: discrete-model/intro.qmd
      chapters:
        - discrete-model/binary-approach.qmd
        - discrete-model/modular-operations.qmd
        - discrete-model/roots-of-unity.qmd
        - discrete-model/index-one-hot.qmd
        - discrete-model/extended-binary-expansion.qmd
        - discrete-model/summary.qmd
        

  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    axe: true
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

# editor: visual