project:
  type: book

book:
  title: "fhe-intro-book"
  author: "camcos-sjsu"
  date: "September 28, 2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: aux-fn.qmd
      chapters:
        - intravector-sums.qmd
        - higher-moments.qmd
        - taylor-approx.qmd
        - sqrt-user-input.qmd
        - logarithm.qmd
    - part: division.qmd
      chapters:
      - geometric-series.qmd
      - newtons-method.qmd
      - hybrid-approach.qmd
      - softmax.qmd
    - part: discrete-math.qmd
    - part: sign-fn.qmd
      chapters:
        - logistic.qmd
        - tanh.qmd
        - sign-appl.qmd
    - part: sorting.qmd
      chapters:
        - bubble.qmd
        - sorting-better.qmd
    - max.qmd
    - part: difference-matrix.qmd
      chapters:
        - mode.qmd
        - median.qmd
    - part: correlation-related.qmd
      chapters:
        - two-coeff.qmd
        - linear-regression.qmd
    - part: other.qmd
      chapters:
        - matrix-multiplication.qmd
        - shannon-entropy.qmd
        - adaptive-division.qmd
        - logarithm-rev.qmd
    - part: lit-review.qmd

  appendices:
    - discrete-computational.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    axe: true
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

# editor: visual