project:
  type: book

book:
  title: "fhe-intro-book"
  author: "camcos-sjsu"
  date:
  chapters:
    - index.qmd
    - about.qmd
    - intro.qmd
    - part: aux-fn.qmd
      chapters:
        - intravector-sums.qmd
        - higher-moments.qmd
        - taylor-approx.qmd
        - sqrt-user-input.qmd
        - logarithm.qmd
    - part: division.qmd
      - geometric-series.qmd
      - newton-method.qmd
      - hybrid.qmd
      - softmax.qmd
    - part: discrete-math.qmd
      chapters:
      - part: sign.qmd
        - logistic.qmd
        - tanh.qmd
        - sign-appl.qmd
      - part: sorting.qmd
        chapters:
          - bubble.qmd
          - sort-improvements.qmd
      - part: max.qmd
      - part: difference-matrix.qmd
        chapters:
          - mode.qmd
          - median.qmd
      - part: correlation-related.qmd
        chapters:
          - two-coeff.qmd
          - linear-regression.qmd
      - part: other.qmd
        chapters:
          - matrix-multiplication.qmd
          - shannon-entropy.qmd
          - adaptive-division.qmd
          - logarithm-rev.qmd
      - part: lit-review.qmd
      appendices:
        - discrete-computational.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual