## V.2 Median

We can employ a similar method to find the median value. For this method, we assume for simplicity that all the numbers are distinct and $N/2$ is odd.
1. Create a matrix $D$ where $$D_{i,j} = \mathtt{sign_{-1, 1,0}}(z_i - z_j).$$ We can just compute the same matrix and then run the sign function over every row. This looks like: \begin{array}{c|ccccc}
  & x_1 & x_2 & x_3 & \cdots & x_{N/2} \\
\hline
x_1 & 0 & -1 & -1 & \cdots & -1 \\
x_2 & 1 & 0 & -1 & \cdots & -1 \\
x_3 & 1 & 1 & 0 & \cdots & -1 \\
\vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
x_{N/2} & 1 & 1 & 1 & \cdots & 0
\end{array} though unlike $D$ from earlier, $\delta_{i,j} \in \{-1, 1\}$. We assume the diagonals are assigned $0$ here.[^distance]

[^distance]: Landon Hurley; **Completing and studentising Spearman’s correlation in the presence of ties** available from https://arxiv.org/pdf/2512.23993

2. Now, if $z_i$ were the median, then it would have an equal number of $-1$s and $1$s in its row, which is equivalent with having row sum $0$ (note that this implicitly assumes that there is no multiplicity of the median; more accurately, the median occurs an odd number of times).
3. Thus, we can get a vector of the sums of the $x_i$ and then compute equality with zero: $$m := ((x_1 + x_2 + \cdots + x_{N/2}) == 0)$$ to obtain a $0$-$1$ vector that points out which *index* the median falls in. 
4. If we are interested in the *value* of the median instead of the *index,* then we can just multiply $\mathtt{sum}(m * z)$. Note that this sum only works if exactly one element is the median: if, say, two elements are the median, then we would get twice the median if we sum.

:::info
**Remarks**:
1. If we want to sort for any reason, then getting the median from the sort is immediate and we would not need to add extra computation.
2. Constructing quartiles is similar to the median. If we use the "sum sign functions" method, then getting a 75% quartile is just finding something with row sum $N/2$ instead of $0$.
:::
Pushing onward, we now extend from univariate summaries to measures of dependence, such as correlation and related functions, which capture relationships between variables.